on: push
name: CI
jobs:
  pest:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          touch database/database.sqlite
          php artisan optimize --env=testing

      - name: Run Testsuite
        run: php artisan test --env=testing
